version: "3.9"

services:
  springxvue:
    container_name: springxvue
    build:
      dockerfile: ./src/main/resources/Dockerfile
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spring-x-vue-db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_DATASOURCE_USERNAME=springxvue
      - SPRING_DATASOURCE_PASSWORD=springxvue
    ports:
      - "8080:8080"
    volumes:
      - spring:/home/user/api
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=springxvue
      - POSTGRES_PASSWORD=springxvue
      - POSTGRES_DB=spring-x-vue-db
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  spring:
